# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Meenakshi Asokan
description: Meenakshi Asokan - Neuroscience
baseurl: "/"
url: ""

email: masokan94@gmail.com
twitter: MeenaMaverick94
#googlescholar: 
#orcid: 
github: Meenakshi-Asokan

# Build settings
markdown: kramdown
permalink: /:categories/:title/

# Posts settings
future: true
safe: false
lsi: false
excerpt_separator: "\n\n"

# Theme settings
compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all

sass:
  sass_dir: assets/_sass
  style: compressed


images: '/assets/images'
papers: '/papers'
